### ISSUE TITLE
Source files from Nettiradio missing BSD-licence

### ISSUE THREAD

**Issue by Jollailija** [nesnomis/harbour-allradio#1]
Just a friendly reminder :)

From a quick browse through, there are five files that have parts of Nettiradio's code: About.qml, Help.qml, PlayerPanel.qml, SleepTimerPage.qml and CoverPage.qml. Please include the copyright notice, the list of conditions and the disclaimer from https://github.com/Jollailija/nettiradio/blob/master/qml/harbour-nettiradio.qml

**Comment by nesnomis** [comment]
Hi,

I have reviewed and looked at your code, and have come to the conclusion
that they are not similar in a way that i can change the copyright and
license. Don't take this the wrong way! I understand you want to protect
your application! And in respect for that i have made changes to things i
am guessing you believe are yours?!

So, please check my code again, and let me know if you think it is
copy/pasting and i will look it over again! And just to make sure, AllRadio
is written by my self, but as everyone else i am looking at how other
people are doing some of the clever solutions.

So, to end this answer, once again, dont take it the wrong way, but i have
put a lot of hours into AllRadio (and i believe i can call it my own!).

Kind Regards

nesnomis

2015-08-26 17:19 GMT+02:00 jollailija notifications@github.com:
