### ISSUE TITLE
Update newer api  

### ISSUE THREAD

**Issue by carlosgonz0** [nesnomis/harbour-allradio#23]
[ Message from CRS ]  If  still use the api at www.radio-browser.info/webservice you should switch as soon as possible to the new one at api.radio-browser.info. The old one is not supported anymore and will not receive any more updates on the software side. The new one is in place and stronger than ever (multiple servers). The api endpoints at www.radio-browser.info/webservice will be taken down at August 1. of 2020.

**Comment by nesnomis** [comment]
Yes i am aware! And i am working on a new version of AllRadio.... :)

**Comment by GNUuser** [comment]
You are hero. Thank you.

**Comment by carlosgonz0** [comment]
Too much time i close this. #26
