### ISSUE TITLE
// 

### ISSUE THREAD

**Issue by ghost** [nesnomis/harbour-allradio#6]
- I have several day translating to spanish this great apps. But too many strings of word to translate on the same sentence.

**Comment by eson57** [comment]
You do not need SFOS SDK to use Qt linguist. In fact, I think SDK will complicate things if you do not develop apps but only want to translate.

Instead you could download and install stand alone Qt linguist. Windows [installer is here](https://github.com/thurask/Qt-Linguist/releases). For Linux you'll find it in your software repository. For example, Debian based distributions you just install `qt4-linguist-tools` package.

**Comment by Caballlero** [comment]
- I used the sdk to deploy app,actually i am learning programing slowly ,it is lot thing to learn, to be a developer. But I still have not arrived at linguist qt. 
- Thank you very much to help me.
# eson57

**Comment by eson57** [comment]
Ok, then I wish you good luck! I am actually doing the same, slowly learning programming, so I know there is a lot to learn.
